#!/usr/bin/env python
"""
Generate the B-GEN genomics suite configs (PRD: brain/plans/B-GEN_genomics_PRD.md): the genomics
arch-reversal experiment = attention(gpt2) vs SSM(mamba) × scales {S,M} × seeds {0,1,2} = 12 configs,
each with log-spaced intermediate checkpoints (the trajectory the rank-reversal analysis needs).

This REUSES the release config builder (`scripts.gen_release_configs._build_config_dict` + GRID), then
overrides only the genomics-specific fields, so the architecture/optimizer/scaling recipe is *identical*
to the protein suite — a controlled cross-domain replication where only the domain changes:
  tokenizer -> genome (10-token {A,C,G,T,N}+specials),  model.vocab_size -> 10,
  model.max_seq_len -> 1024 (genomic window),  data -> hg38 shards,  ckpt_root -> genome_traj.
Trajectory save-steps are recomputed from the *genome* parameter count.

Only WRITES configs (configs/genome/); launches nothing. Submit with runs/genome_train.slurm when
the hg38 shards exist and a GPU is free (the tokenizer train-path is smoke-tested first).

Usage:
  python -m scripts.gen_genome_configs                          # 12 configs (gpt2,mamba × S,M × s0-2)
  python -m scripts.gen_genome_configs --scales S M --seeds 0 1 2 --archs gpt2 mamba
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Dict, List

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from nanoprot.config import NanoprotConfig  # noqa: E402
from scripts.gen_release_configs import (  # noqa: E402
    _build_config_dict, _validate, _dump_yaml, _log_spaced_steps,
    PARAM_DATA_RATIO, TOTAL_BATCH_SIZE, N_INTERMEDIATE,
)

GENOME_VOCAB = 10      # GenomeTokenizer: {A,C,G,T,N} + <cls>/<pad>/<eos>/<unk>/<mask>
GENOME_CTX = 1024      # genomic window (bp) = context length
GENOME_ARCHS = ["gpt2", "mamba"]   # the arch-reversal pair (no esm2 for B-GEN)
GENOME_SCALES = ["S", "M"]


def _genome_config(arch: str, scale: str, seed: int, n_intermediate: int) -> Dict[str, Any]:
    cfg = _build_config_dict(arch, scale, seed, intermediate=False, ckpt_root="genome_traj",
                             full_logging=True, eval_every=50, eval_tokens_mult=8)
    name = f"genome-{arch}-{scale}-s{seed}"
    cfg["name"] = name
    cfg["tokenizer"] = {"name": "genome"}
    cfg["model"]["vocab_size"] = GENOME_VOCAB
    cfg["model"]["max_seq_len"] = GENOME_CTX
    cfg["data"] = dict(dataset="hg38", shard_dir="${NANOPROT_BASE_DIR}/hg38_parquet",
                       packing="bos_aligned_best_fit", val_shard="last")
    cfg["logging"]["run_name"] = name
    cfg["checkpointing"]["output_dir"] = f"${{NANOPROT_BASE_DIR}}/genome_traj/{name}"
    # Recompute the log-spaced trajectory checkpoints from the GENOME parameter count.
    probe = NanoprotConfig(name=name, seed=seed, model=dict(cfg["model"]),
                           tokenizer={"name": "genome"}, data={"shard_dir": "/tmp"},
                           checkpointing={"output_dir": "/tmp"}, training=dict(cfg["training"]))
    n_iter_est = int(PARAM_DATA_RATIO * probe.estimate_params() // TOTAL_BATCH_SIZE)
    cfg["checkpointing"]["save_steps"] = _log_spaced_steps(n_iter_est, n_intermediate)
    return cfg


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, default=Path("configs/genome"))
    ap.add_argument("--archs", nargs="+", default=GENOME_ARCHS, choices=["gpt2", "mamba"])
    ap.add_argument("--scales", nargs="+", default=GENOME_SCALES, choices=["XS", "S", "M", "L"])
    ap.add_argument("--seeds", type=int, nargs="+", default=[0, 1, 2])
    ap.add_argument("--n-intermediate", type=int, default=N_INTERMEDIATE)
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    if args.out.exists() and any(args.out.glob("*.yaml")) and not args.force:
        sys.exit(f"{args.out} already contains configs; pass --force to overwrite.")

    manifest: List[str] = ["name\tarch\tscale\tseed\tdepth\td_model\tvocab\tctx\test_params\tnum_iter_est"]
    summary: List[str] = []
    n = 0
    for arch in args.archs:
        for scale in args.scales:
            for seed in args.seeds:
                cfg = _genome_config(arch, scale, seed, args.n_intermediate)
                validated = _validate(cfg)                      # raises on schema error
                est = validated.estimate_params()
                n_iter = int(PARAM_DATA_RATIO * est // TOTAL_BATCH_SIZE)
                name = cfg["name"]
                banner = (
                    f"# AUTO-GENERATED by scripts/gen_genome_configs.py — DO NOT EDIT BY HAND.\n"
                    f"# B-GEN genomics: {arch} {scale} (seed {seed}); tokenizer=genome (V={GENOME_VOCAB}), "
                    f"ctx={GENOME_CTX}.\n"
                    f"# ~{est/1e6:.1f}M params, ~{n_iter:,} steps, objective=ar.\n"
                    f"# Regenerate: python -m scripts.gen_genome_configs\n\n"
                )
                _dump_yaml(cfg, args.out / f"{name}.yaml", banner)
                manifest.append(f"{name}\t{arch}\t{scale}\t{seed}\t{validated.model.depth}\t"
                                f"{validated.model.d_model}\t{GENOME_VOCAB}\t{GENOME_CTX}\t{est}\t{n_iter}")
                n += 1
                if seed == args.seeds[0]:
                    summary.append(f"  {arch:>5} {scale:>2}: depth={validated.model.depth:>2} "
                                   f"d={validated.model.d_model:>4} ~{est/1e6:6.1f}M ~{n_iter:>6,} steps")
    (args.out / "MANIFEST.tsv").write_text("\n".join(manifest) + "\n")
    print(f"Wrote {n} genomics configs to {args.out}/  (MANIFEST.tsv)")
    print("\n".join(summary))
    print(f"\nNext: ensure hg38 shards exist (scripts.prepare_genome), smoke-test the genome tokenizer "
          f"train-path on a GPU, then submit runs/genome_train.slurm.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
